title: Bulk Add to Project
description: This DocumentCloud Add-On allows you to add a query of documents to a project. 
type: object
documents:
  - query
properties:
  project_id:
    title: Project ID
    type: integer
version: 2
